title: "SLDReader"
remote_theme: pmarsceill/just-the-docs
search_enabled: false
theme: "just-the-docs"
sass:
  style: compressed
aux_links:
  "SLDReader on GitHub":
    - "//github.com/nieuwlandgeo/sldreader"